test-ruby-21:
        image: tcnksm/centos-ruby:2.1
        stage: test
        tags:
                - docker
        script:
                - yum install -y rpm
                - bundle install
                - bundle exec rake spec

