test-ruby-21:
        image: ruby:2.1
        stage: test
        tags:
                - docker
                - shared
        script:
                - bundle install
                - bundle exec rake spec

