test-ruby-21:
        image: simpproject/centos6:ruby2.1
        stage: test
        tags:
                - docker
        script:
                - bundle install
                - bundle exec rake spec

