test-ruby-21:
        image: simpproject/centos6:ruby21
        stage: test
        tags:
                - docker
                - shared
        script:
                - bundle install
                - bundle exec rake spec
acceptance-test-r10k:
  stage: test
  tags:
    - beaker
  script:
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake beaker:suites[default]
acceptance-test-inspec:
  stage: test
  tags:
    - beaker
  script:
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake beaker:suites[compliance]
